export const HOTSPOT_META = {
  headlight:     { label: 'Headlight Controls', icon: 'Lightbulb',    side: 'right', camera: 'headlight',      view: 'exterior' },
  adas:          { label: 'ADAS System',         icon: 'ShieldCheck',  side: 'right', camera: 'adas',           view: 'exterior' },
  wiper:         { label: 'Wiper Controls',      icon: 'Droplets',     side: 'right', camera: 'wiper',          view: 'exterior' },
  mirror_left:   { label: 'Left Mirror & BSM',   icon: 'Eye',          side: 'right', camera: 'mirror_left',    view: 'exterior' },
  mirror_right:  { label: 'Right Mirror & BSM',  icon: 'Eye',          side: 'left',  camera: 'mirror_right',   view: 'exterior' },
  bumper:        { label: 'Parking Sensors',      icon: 'ScanLine',     side: 'right', camera: 'bumper',         view: 'exterior' },
  foglight:      { label: 'Fog & Corner Lights', icon: 'Layers',       side: 'right', camera: 'foglight',       view: 'exterior' },
  sunroof:       { label: 'Panoramic Sunroof',   icon: 'Sun',          side: 'right', camera: 'sunroof',        view: 'exterior' },
  door:          { label: 'Door Management',     icon: 'DoorOpen',     side: 'right', camera: 'door',           view: 'exterior' },
  taillight:     { label: 'Rear Lighting',       icon: 'Zap',          side: 'right', camera: 'taillight',      view: 'exterior' },
  boot:          { label: 'Boot Control',        icon: 'DoorOpen',     side: 'right', camera: 'boot',           view: 'exterior' },
  bonnet:        { label: 'Hood Control',        icon: 'Wrench',       side: 'right', camera: 'bonnet',         view: 'exterior' },
  ac_vent:       { label: 'Climate Control',     icon: 'Wind',         side: 'right', camera: 'ac_vent',        view: 'interior' },
  seat_driver:   { label: 'Driver Seat',         icon: 'Armchair',     side: 'right', camera: 'seat_driver',    view: 'interior' },
  seat_passenger:{ label: 'Passenger Seat',      icon: 'Armchair',     side: 'left',  camera: 'seat_passenger', view: 'interior' },
  steering:      { label: 'Steering Wheel',      icon: 'Gauge',        side: 'right', camera: 'steering',       view: 'interior' },
  infotainment:  { label: 'Infotainment',        icon: 'Monitor',      side: 'right', camera: 'infotainment',   view: 'interior' },
  ambient:       { label: 'Ambient Lighting',    icon: 'Palette',      side: 'right', camera: 'ambient',        view: 'interior' },
  instrument:    { label: 'Instrument Cluster',  icon: 'BarChart2',    side: 'right', camera: 'instrument',     view: 'interior' },
  overhead:      { label: 'Overhead Console',    icon: 'Lamp',         side: 'right', camera: 'overhead',       view: 'interior' },
}

// Exterior mesh name → hotspot key (used by VehicleModel raycaster)
export const EXTERIOR_MESH_TO_HOTSPOT = {
  adas_camera:       'adas',
  headlight_l:       'headlight',
  headlight_r:       'headlight',
  taillight_l:       'taillight',
  taillight_r:       'taillight',
  foglight_l:        'foglight',
  foglight_r:        'foglight',
  wiper_front_left:  'wiper',
  wiper_front_right: 'wiper',
  wiper_rear:        'wiper',
  mirror_left:       'mirror_left',
  mirror_right:      'mirror_right',
  door_fl:           'door',
  door_fr:           'door',
  door_rl:           'door',
  door_rr:           'door',
  bumper_front:      'bumper',
  bumper_rear:       'bumper',
  bonnet:            'bonnet',
  boot:              'boot',
  roof:              'sunroof',
}

// Interior mesh name → hotspot key (used by InteriorModel click handlers)
export const INTERIOR_MESH_TO_HOTSPOT = {
  ac_vent_l:          'ac_vent',
  ac_vent_r:          'ac_vent',
  ac_vent_c:          'ac_vent',
  seat_driver:        'seat_driver',
  seat_passenger:     'seat_passenger',
  steering_wheel:     'steering',
  screen_main:        'infotainment',
  ambient_strip:      'ambient',
  instrument_cluster: 'instrument',
  overhead_console:   'overhead',
}
