// Material values tuned for MeshPhysicalMaterial + clearcoat pipeline.
// Three.js Ferrari example uses metalness:1.0, roughness:0.5 on the body.
// We keep per-colour roughness for variety while clearcoat unifies the gloss.
export const PAINT_COLORS = [
  {
    id: 'pearl-white',
    name: 'Platinum White Pearl',
    hex: '#F0EEE9',
    metalness: 0.50,   // pearl = semi-metallic
    roughness: 0.38,
    envIntensity: 1.0,
    scene: {
      background:    '#0d1017',
      fogColor:      '#0a0d13',
      groundColor:   '#07090e',
      gridColor:     '#182038',
      rimLightColor: '#a0c4ff',
    },
  },
  {
    id: 'obsidian-black',
    name: 'Obsidian Black Pearl',
    hex: '#1C1C20',
    metalness: 1.00,
    roughness: 0.44,
    envIntensity: 1.0,
    scene: {
      background:    '#020204',
      fogColor:      '#030305',
      groundColor:   '#010103',
      gridColor:     '#0a1828',
      rimLightColor: '#00d4ff',
    },
  },
  {
    id: 'radiant-red',
    name: 'Radiant Red Metallic',
    hex: '#9B1C1C',
    metalness: 1.00,
    roughness: 0.48,
    envIntensity: 1.0,
    scene: {
      background:    '#0f0608',
      fogColor:      '#0c0406',
      groundColor:   '#080304',
      gridColor:     '#280a0a',
      rimLightColor: '#ff7050',
    },
  },
  {
    id: 'lunar-silver',
    name: 'Lunar Silver Metallic',
    hex: '#8A8F96',
    metalness: 1.00,
    roughness: 0.46,
    envIntensity: 1.0,
    scene: {
      background:    '#0a0c10',
      fogColor:      '#08090d',
      groundColor:   '#06080c',
      gridColor:     '#182030',
      rimLightColor: '#c0d8ff',
    },
  },
  {
    id: 'aegean-blue',
    name: 'Aegean Blue Metallic',
    hex: '#1A3A6C',
    metalness: 1.00,
    roughness: 0.46,
    envIntensity: 1.0,
    scene: {
      background:    '#04060e',
      fogColor:      '#03050b',
      groundColor:   '#020407',
      gridColor:     '#081428',
      rimLightColor: '#40a8ff',
    },
  },
  {
    id: 'sonic-grey',
    name: 'Sonic Grey Pearl',
    hex: '#4A4E54',
    metalness: 1.00,
    roughness: 0.50,
    envIntensity: 1.0,
    scene: {
      background:    '#080808',
      fogColor:      '#060606',
      groundColor:   '#040404',
      gridColor:     '#161618',
      rimLightColor: '#90b0c8',
    },
  },
  {
    id: 'platinum-bronze',
    name: 'Platinum Bronze Metallic',
    hex: '#7A5C3A',
    metalness: 1.00,
    roughness: 0.48,
    envIntensity: 1.0,
    scene: {
      background:    '#0a0804',
      fogColor:      '#080603',
      groundColor:   '#060401',
      gridColor:     '#1e1408',
      rimLightColor: '#d4a060',
    },
  },
  {
    id: 'aurora-green',
    name: 'Aurora Green Metallic',
    hex: '#1A4A2E',
    metalness: 1.00,
    roughness: 0.48,
    envIntensity: 1.0,
    scene: {
      background:    '#040a05',
      fogColor:      '#030704',
      groundColor:   '#020402',
      gridColor:     '#0a1c0c',
      rimLightColor: '#40e880',
    },
  },
]
